// Package server contains generated server stubs from the OpenAPI specification.
// DO NOT EDIT MANUALLY - generated by oapi-codegen
// To regenerate: go generate ./...
package server

//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config=../../../config/oapi-codegen-server.yaml ../../../config/openapi.yaml
