// Package slurmclient contains generated client code for the Slurm REST API.
// DO NOT EDIT MANUALLY - generated by oapi-codegen from config/openapi/slurm/slurm-openapi-v0.0.37.json
// To regenerate: go generate ./...
package slurmclient

//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config=../../config/openapi/slurm/oapi-codegen-slurm-client.yaml ../../config/openapi/slurm/slurm-openapi-v0.0.37.json
