// Package types contains generated types from the OpenAPI specification.
// DO NOT EDIT MANUALLY - generated by oapi-codegen
// To regenerate: go generate ./...
package types

//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config=../../../oapi-codegen-types.yaml ../../../openapi.yaml
