// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package types

import (
	"time"
)

// Defines values for HealthResponseStatus.
const (
	Degraded  HealthResponseStatus = "degraded"
	Healthy   HealthResponseStatus = "healthy"
	Unhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for JobState.
const (
	Cancelled JobState = "cancelled"
	Completed JobState = "completed"
	Failed    JobState = "failed"
	Pending   JobState = "pending"
	Running   JobState = "running"
)

// CreateJobRequest defines model for CreateJobRequest.
type CreateJobRequest struct {
	// Id Unique job identifier
	Id string `json:"id"`

	// Nodes List of node names to allocate
	Nodes []string `json:"nodes"`

	// User User who submitted the job
	User string `json:"user"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Details Additional error details
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Error code
	Error string `json:"error"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Current health status of the service
	Status HealthResponseStatus `json:"status"`

	// Timestamp Time of health check
	Timestamp time.Time `json:"timestamp"`

	// Version Service version
	Version *string `json:"version,omitempty"`
}

// HealthResponseStatus Current health status of the service
type HealthResponseStatus string

// Job defines model for Job.
type Job struct {
	// CpuUsage Current CPU usage percentage
	CpuUsage *float64 `json:"cpu_usage,omitempty"`

	// EndTime Job end time (if completed or failed)
	EndTime *time.Time `json:"end_time,omitempty"`

	// GpuUsage Current GPU usage percentage (optional)
	GpuUsage *float64 `json:"gpu_usage,omitempty"`

	// Id Unique job identifier
	Id string `json:"id"`

	// MemoryUsageMb Current memory usage in megabytes
	MemoryUsageMb *int `json:"memory_usage_mb,omitempty"`

	// Nodes List of node names allocated to the job
	Nodes []string `json:"nodes"`

	// RuntimeSeconds Total runtime in seconds
	RuntimeSeconds *float64 `json:"runtime_seconds,omitempty"`

	// StartTime Job start time
	StartTime time.Time `json:"start_time"`

	// State Current state of the job
	State JobState `json:"state"`

	// User User who submitted the job
	User string `json:"user"`
}

// JobListResponse defines model for JobListResponse.
type JobListResponse struct {
	Jobs []Job `json:"jobs"`

	// Limit Maximum number of jobs returned
	Limit int `json:"limit"`

	// Offset Number of jobs skipped
	Offset int `json:"offset"`

	// Total Total number of jobs matching the filter
	Total int `json:"total"`
}

// JobMetricsResponse defines model for JobMetricsResponse.
type JobMetricsResponse struct {
	// JobId Job identifier
	JobId   string         `json:"job_id"`
	Samples []MetricSample `json:"samples"`

	// Total Total number of samples returned
	Total int `json:"total"`
}

// JobState Current state of the job
type JobState string

// MetricSample defines model for MetricSample.
type MetricSample struct {
	// CpuUsage CPU usage percentage at this point in time
	CpuUsage float64 `json:"cpu_usage"`

	// GpuUsage GPU usage percentage at this point in time (optional)
	GpuUsage *float64 `json:"gpu_usage,omitempty"`

	// MemoryUsageMb Memory usage in megabytes at this point in time
	MemoryUsageMb int `json:"memory_usage_mb"`

	// Timestamp Time when the sample was recorded
	Timestamp time.Time `json:"timestamp"`
}

// RecordMetricsRequest defines model for RecordMetricsRequest.
type RecordMetricsRequest struct {
	// CpuUsage CPU usage percentage
	CpuUsage float64 `json:"cpu_usage"`

	// GpuUsage GPU usage percentage (optional)
	GpuUsage *float64 `json:"gpu_usage,omitempty"`

	// MemoryUsageMb Memory usage in megabytes
	MemoryUsageMb int `json:"memory_usage_mb"`
}

// UpdateJobRequest defines model for UpdateJobRequest.
type UpdateJobRequest struct {
	CpuUsage      *float64 `json:"cpu_usage,omitempty"`
	GpuUsage      *float64 `json:"gpu_usage,omitempty"`
	MemoryUsageMb *int     `json:"memory_usage_mb,omitempty"`

	// State Current state of the job
	State *JobState `json:"state,omitempty"`
}

// JobId defines model for JobId.
type JobId = string

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	// State Filter by job state
	State *JobState `form:"state,omitempty" json:"state,omitempty"`

	// User Filter by user
	User *string `form:"user,omitempty" json:"user,omitempty"`

	// Node Filter by node name
	Node *string `form:"node,omitempty" json:"node,omitempty"`

	// Limit Maximum number of jobs to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of jobs to skip for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetJobMetricsParams defines parameters for GetJobMetrics.
type GetJobMetricsParams struct {
	// StartTime Start of time range (RFC3339 format)
	StartTime *time.Time `form:"start_time,omitempty" json:"start_time,omitempty"`

	// EndTime End of time range (RFC3339 format)
	EndTime *time.Time `form:"end_time,omitempty" json:"end_time,omitempty"`

	// Limit Maximum number of samples to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody = CreateJobRequest

// UpdateJobJSONRequestBody defines body for UpdateJob for application/json ContentType.
type UpdateJobJSONRequestBody = UpdateJobRequest

// RecordJobMetricsJSONRequestBody defines body for RecordJobMetrics for application/json ContentType.
type RecordJobMetricsJSONRequestBody = RecordMetricsRequest
