// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package types

import (
	"time"
)

// Defines values for GPUVendor.
const (
	Amd    GPUVendor = "amd"
	Mixed  GPUVendor = "mixed"
	None   GPUVendor = "none"
	Nvidia GPUVendor = "nvidia"
)

// Defines values for HealthResponseStatus.
const (
	Degraded  HealthResponseStatus = "degraded"
	Healthy   HealthResponseStatus = "healthy"
	Unhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for JobEventResponseStatus.
const (
	Created JobEventResponseStatus = "created"
	Skipped JobEventResponseStatus = "skipped"
	Updated JobEventResponseStatus = "updated"
)

// Defines values for JobState.
const (
	Cancelled JobState = "cancelled"
	Completed JobState = "completed"
	Failed    JobState = "failed"
	Pending   JobState = "pending"
	Running   JobState = "running"
)

// Defines values for SchedulerInfoType.
const (
	Mock  SchedulerInfoType = "mock"
	Slurm SchedulerInfoType = "slurm"
)

// CreateJobRequest defines model for CreateJobRequest.
type CreateJobRequest struct {
	// Id Unique job identifier
	Id string `json:"id"`

	// Nodes List of node names to allocate
	Nodes []string `json:"nodes"`

	// Scheduler Metadata from the external workload manager (e.g., SLURM).
	// This information is populated when jobs are synced from an external scheduler.
	Scheduler *SchedulerInfo `json:"scheduler,omitempty"`

	// User User who submitted the job
	User string `json:"user"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Details Additional error details
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Error code
	Error string `json:"error"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// GPUVendor GPU vendor type
type GPUVendor string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Current health status of the service
	Status HealthResponseStatus `json:"status"`

	// Timestamp Time of health check
	Timestamp time.Time `json:"timestamp"`

	// Version Service version
	Version *string `json:"version,omitempty"`
}

// HealthResponseStatus Current health status of the service
type HealthResponseStatus string

// Job defines model for Job.
type Job struct {
	// AllocatedCpus CPUs allocated to the job
	AllocatedCpus *int `json:"allocated_cpus,omitempty"`

	// AllocatedGpus GPUs allocated to the job
	AllocatedGpus *int `json:"allocated_gpus,omitempty"`

	// AllocatedMemoryMb Memory allocated to the job (MB)
	AllocatedMemoryMb *int `json:"allocated_memory_mb,omitempty"`

	// AvgCpuUsage Average CPU usage across samples
	AvgCpuUsage *float64 `json:"avg_cpu_usage,omitempty"`

	// AvgGpuUsage Average GPU usage across samples
	AvgGpuUsage *float64 `json:"avg_gpu_usage,omitempty"`

	// ClusterName Cluster identifier for multi-cluster deployments
	ClusterName *string `json:"cluster_name,omitempty"`

	// CpuUsage Current CPU usage percentage
	CpuUsage *float64 `json:"cpu_usage,omitempty"`

	// EndTime Job end time (if completed or failed)
	EndTime *time.Time `json:"end_time,omitempty"`

	// GpuUsage Current GPU usage percentage (optional)
	GpuUsage *float64 `json:"gpu_usage,omitempty"`

	// Id Unique job identifier
	Id string `json:"id"`

	// IngestVersion Ingestion pipeline version
	IngestVersion *string `json:"ingest_version,omitempty"`

	// LastSampleAt Timestamp of the latest metrics sample
	LastSampleAt *time.Time `json:"last_sample_at,omitempty"`

	// MaxCpuUsage Maximum CPU usage across samples
	MaxCpuUsage *float64 `json:"max_cpu_usage,omitempty"`

	// MaxGpuUsage Maximum GPU usage across samples
	MaxGpuUsage *float64 `json:"max_gpu_usage,omitempty"`

	// MaxMemoryUsageMb Maximum memory usage across samples (MB)
	MaxMemoryUsageMb *int `json:"max_memory_usage_mb,omitempty"`

	// MemoryUsageMb Current memory usage in megabytes
	MemoryUsageMb *int `json:"memory_usage_mb,omitempty"`

	// NodeCount Number of nodes allocated to the job
	NodeCount *int `json:"node_count,omitempty"`

	// Nodes List of node names allocated to the job
	Nodes []string `json:"nodes"`

	// RequestedCpus CPUs requested by the job
	RequestedCpus *int `json:"requested_cpus,omitempty"`

	// RequestedGpus GPUs requested by the job
	RequestedGpus *int `json:"requested_gpus,omitempty"`

	// RequestedMemoryMb Memory requested by the job (MB)
	RequestedMemoryMb *int `json:"requested_memory_mb,omitempty"`

	// RuntimeSeconds Total runtime in seconds
	RuntimeSeconds *float64 `json:"runtime_seconds,omitempty"`

	// SampleCount Total number of metrics samples recorded for the job
	SampleCount *int `json:"sample_count,omitempty"`

	// Scheduler Metadata from the external workload manager (e.g., SLURM).
	// This information is populated when jobs are synced from an external scheduler.
	Scheduler *SchedulerInfo `json:"scheduler,omitempty"`

	// SchedulerInstance Scheduler instance identifier
	SchedulerInstance *string `json:"scheduler_instance,omitempty"`

	// StartTime Job start time
	StartTime time.Time `json:"start_time"`

	// State Current state of the job
	State JobState `json:"state"`

	// User User who submitted the job
	User string `json:"user"`
}

// JobEventResponse defines model for JobEventResponse.
type JobEventResponse struct {
	// JobId Job identifier
	JobId string `json:"job_id"`

	// Message Optional message with details
	Message *string `json:"message,omitempty"`

	// Status Result of processing the event
	Status JobEventResponseStatus `json:"status"`
}

// JobEventResponseStatus Result of processing the event
type JobEventResponseStatus string

// JobFinishedEvent Event emitted by Slurm epilog script when a job finishes
type JobFinishedEvent struct {
	// ExitCode Job exit code
	ExitCode *int `json:"exit_code,omitempty"`

	// FinalState Current state of the job
	FinalState JobState `json:"final_state"`

	// JobId Slurm job ID
	JobId string `json:"job_id"`

	// Signal Signal that killed the job (if applicable)
	Signal *int `json:"signal,omitempty"`

	// Timestamp Event timestamp
	Timestamp time.Time `json:"timestamp"`
}

// JobListResponse defines model for JobListResponse.
type JobListResponse struct {
	Jobs []Job `json:"jobs"`

	// Limit Maximum number of jobs returned
	Limit int `json:"limit"`

	// Offset Number of jobs skipped
	Offset int `json:"offset"`

	// Total Total number of jobs matching the filter
	Total int `json:"total"`
}

// JobMetricsResponse defines model for JobMetricsResponse.
type JobMetricsResponse struct {
	// JobId Job identifier
	JobId   string         `json:"job_id"`
	Samples []MetricSample `json:"samples"`

	// Total Total number of samples returned
	Total int `json:"total"`
}

// JobStartedEvent Event emitted by Slurm prolog script when a job starts
type JobStartedEvent struct {
	// Account Slurm account name
	Account *string `json:"account,omitempty"`

	// CgroupPath Path to the job's cgroup
	CgroupPath *string `json:"cgroup_path,omitempty"`

	// CpuAllocation Number of CPUs allocated
	CpuAllocation *int `json:"cpu_allocation,omitempty"`

	// GpuAllocation Number of GPUs allocated
	GpuAllocation *int `json:"gpu_allocation,omitempty"`

	// GpuDevices GPU device identifiers (UUIDs or card IDs)
	GpuDevices *[]string `json:"gpu_devices,omitempty"`

	// GpuVendor GPU vendor type
	GpuVendor *GPUVendor `json:"gpu_vendor,omitempty"`

	// JobId Slurm job ID
	JobId string `json:"job_id"`

	// MemoryAllocationMb Memory allocated in MB
	MemoryAllocationMb *int `json:"memory_allocation_mb,omitempty"`

	// NodeList List of nodes allocated to the job
	NodeList []string `json:"node_list"`

	// Partition Slurm partition name
	Partition *string `json:"partition,omitempty"`

	// Timestamp Event timestamp
	Timestamp time.Time `json:"timestamp"`

	// User User who submitted the job
	User string `json:"user"`
}

// JobState Current state of the job
type JobState string

// MetricSample defines model for MetricSample.
type MetricSample struct {
	// CpuUsage CPU usage percentage at this point in time
	CpuUsage float64 `json:"cpu_usage"`

	// GpuUsage GPU usage percentage at this point in time (optional)
	GpuUsage *float64 `json:"gpu_usage,omitempty"`

	// MemoryUsageMb Memory usage in megabytes at this point in time
	MemoryUsageMb int `json:"memory_usage_mb"`

	// Timestamp Time when the sample was recorded
	Timestamp time.Time `json:"timestamp"`
}

// RecordMetricsRequest defines model for RecordMetricsRequest.
type RecordMetricsRequest struct {
	// CpuUsage CPU usage percentage
	CpuUsage float64 `json:"cpu_usage"`

	// GpuUsage GPU usage percentage (optional)
	GpuUsage *float64 `json:"gpu_usage,omitempty"`

	// MemoryUsageMb Memory usage in megabytes
	MemoryUsageMb int `json:"memory_usage_mb"`
}

// SchedulerInfo Metadata from the external workload manager (e.g., SLURM).
// This information is populated when jobs are synced from an external scheduler.
type SchedulerInfo struct {
	// Account Account/project charged for the job
	Account *string `json:"account,omitempty"`

	// ExitCode Job exit code (available after completion)
	ExitCode *int `json:"exit_code,omitempty"`

	// ExternalJobId Job ID in the external scheduler (e.g., SLURM job_id)
	ExternalJobId *string `json:"external_job_id,omitempty"`

	// Extra Additional scheduler-specific metadata
	Extra *map[string]interface{} `json:"extra,omitempty"`

	// Partition Scheduler partition/queue name
	Partition *string `json:"partition,omitempty"`

	// Priority Job priority in the scheduler queue (Slurm uses uint32 which may exceed int32)
	Priority *int64 `json:"priority,omitempty"`

	// Qos Quality of Service level
	Qos *string `json:"qos,omitempty"`

	// RawState Original state string from the scheduler before normalization.
	// For SLURM: PENDING, RUNNING, COMPLETED, FAILED, CANCELLED, TIMEOUT, NODE_FAIL, etc.
	RawState *string `json:"raw_state,omitempty"`

	// StateReason Scheduler-provided reason for state transitions
	StateReason *string `json:"state_reason,omitempty"`

	// SubmitTime Time when the job was submitted to the scheduler
	SubmitTime *time.Time `json:"submit_time,omitempty"`

	// TimeLimitMinutes Time limit in minutes
	TimeLimitMinutes *int `json:"time_limit_minutes,omitempty"`

	// Type Type of scheduler that manages this job
	Type *SchedulerInfoType `json:"type,omitempty"`
}

// SchedulerInfoType Type of scheduler that manages this job
type SchedulerInfoType string

// UpdateJobRequest defines model for UpdateJobRequest.
type UpdateJobRequest struct {
	CpuUsage      *float64 `json:"cpu_usage,omitempty"`
	GpuUsage      *float64 `json:"gpu_usage,omitempty"`
	MemoryUsageMb *int     `json:"memory_usage_mb,omitempty"`

	// State Current state of the job
	State *JobState `json:"state,omitempty"`
}

// ChangedByHeader defines model for ChangedByHeader.
type ChangedByHeader = string

// CorrelationIdHeader defines model for CorrelationIdHeader.
type CorrelationIdHeader = string

// JobId defines model for JobId.
type JobId = string

// SourceHeader defines model for SourceHeader.
type SourceHeader = string

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	// State Filter by job state
	State *JobState `form:"state,omitempty" json:"state,omitempty"`

	// User Filter by user
	User *string `form:"user,omitempty" json:"user,omitempty"`

	// Node Filter by node name
	Node *string `form:"node,omitempty" json:"node,omitempty"`

	// Limit Maximum number of jobs to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of jobs to skip for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateJobParams defines parameters for CreateJob.
type CreateJobParams struct {
	// XChangedBy Identifier of the actor/system performing the change
	XChangedBy ChangedByHeader `json:"X-Changed-By"`

	// XSource Source system initiating the change (api, syncer, scheduler)
	XSource SourceHeader `json:"X-Source"`

	// XCorrelationId Correlation ID for tracing multi-step updates
	XCorrelationId *CorrelationIdHeader `json:"X-Correlation-Id,omitempty"`
}

// DeleteJobParams defines parameters for DeleteJob.
type DeleteJobParams struct {
	// XChangedBy Identifier of the actor/system performing the change
	XChangedBy ChangedByHeader `json:"X-Changed-By"`

	// XSource Source system initiating the change (api, syncer, scheduler)
	XSource SourceHeader `json:"X-Source"`

	// XCorrelationId Correlation ID for tracing multi-step updates
	XCorrelationId *CorrelationIdHeader `json:"X-Correlation-Id,omitempty"`
}

// UpdateJobParams defines parameters for UpdateJob.
type UpdateJobParams struct {
	// XChangedBy Identifier of the actor/system performing the change
	XChangedBy ChangedByHeader `json:"X-Changed-By"`

	// XSource Source system initiating the change (api, syncer, scheduler)
	XSource SourceHeader `json:"X-Source"`

	// XCorrelationId Correlation ID for tracing multi-step updates
	XCorrelationId *CorrelationIdHeader `json:"X-Correlation-Id,omitempty"`
}

// GetJobMetricsParams defines parameters for GetJobMetrics.
type GetJobMetricsParams struct {
	// StartTime Start of time range (RFC3339 format)
	StartTime *time.Time `form:"start_time,omitempty" json:"start_time,omitempty"`

	// EndTime End of time range (RFC3339 format)
	EndTime *time.Time `form:"end_time,omitempty" json:"end_time,omitempty"`

	// Limit Maximum number of samples to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// JobFinishedEventJSONRequestBody defines body for JobFinishedEvent for application/json ContentType.
type JobFinishedEventJSONRequestBody = JobFinishedEvent

// JobStartedEventJSONRequestBody defines body for JobStartedEvent for application/json ContentType.
type JobStartedEventJSONRequestBody = JobStartedEvent

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody = CreateJobRequest

// UpdateJobJSONRequestBody defines body for UpdateJob for application/json ContentType.
type UpdateJobJSONRequestBody = UpdateJobRequest

// RecordJobMetricsJSONRequestBody defines body for RecordJobMetrics for application/json ContentType.
type RecordJobMetricsJSONRequestBody = RecordMetricsRequest
